name: Deploy Javadoc

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - gh-pages

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.push.outputs.status }}
    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: microsoft

      - name: Generate Javadoc with Gradle
        run: ./gradlew javadoc

      - name: Checkout Gh Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          clean: false

      - name: Copy Javadoc
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          FOLDER_NAME="${REF_NAME////-}"
          rm -rf ./_site/javadoc/${FOLDER_NAME}
          mkdir -p ./_site/javadoc
          cp -a ./build/docs/javadoc ./_site/javadoc/${FOLDER_NAME}

      - name: Commit and Push Javadoc
        id: push
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          FOLDER_NAME="${REF_NAME////-}"
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add ./_site/javadoc/${FOLDER_NAME}
          if ! git commit -m 'update ${FOLDER_NAME}'; then
            echo "status=noop" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          git push
          echo "status=succeed" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ubuntu-latest
    if: ${{ needs.generate-and-push.outputs.status == 'succeed' }}
    steps:
      - name: Upload Files as Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./_site/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
